"""empty message

Revision ID: 3bc23df76241
Revises: a97f1ac09a4b
Create Date: 2019-12-30 08:20:46.641014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc23df76241'
down_revision = 'a97f1ac09a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('photo', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'photo')
    # ### end Alembic commands ###
